### ISSUE TITLE
give you my knees

### ISSUE THREAD

**Issue by mc112611** [wzzzd/text_classifier_pytorch#1]
代码层级结构好清晰啊。

**Comment by wzzzd** [comment]
> 代码层级结构好清晰啊。

哈哈，谢谢。
text classify太多demo了，也就只能靠代码规范来骗点Star了

**Comment by mc112611** [comment]
很强很强，本NLP民工还停留在挑选预训练模型阶段，大佬已经把NLP的对抗神经网络给弄出来了。     感谢分享思路。
